Polars Gotchas

#1 Sorting rows independent of the other columns

My issue needing clarification was simply why the following commands sorted the “salary” column differently. It seemed like an easy point of confusion:

employees.with_columns(pl.col("salary").sort())
employees.with_columns(pl.col("salary").sort(descending=True))

The reason why the first sort isn’t what you want is because the salary column is sorted without the data frame context. In other words, it returns the salary without including the actual contents of the data frame considered. The salary row is sorted, but only within itself. The second sort considers the whole data frame and accurately includes the rightful person with the salary.

In [5]:
import polars as pl

employees = pl.read_csv("employees.csv", try_parse_dates=True)
employees.head(3)

shape: (3, 6)
┌────────────────────┬────────────┬──────────────────────────────┬────────┬──────────────────┬────────────┐
│ name               ┆ department ┆ email                        ┆ salary ┆ years_at_company ┆ start_date │
│ ---                ┆ ---        ┆ ---                          ┆ ---    ┆ ---              ┆ ---        │
│ str                ┆ str        ┆ str                          ┆ i64    ┆ i64              ┆ date       │
╞════════════════════╪════════════╪══════════════════════════════╪════════╪══════════════════╪════════════╡
│ Nicholas Maldonado ┆ CEO        ┆ nicholas.maldonado@polars.io ┆ 250000 ┆ 9                ┆ 2016-07-14 │
│ Michael Fletcher   ┆ Operations ┆ michael.fletcher@polars.io   ┆ 96540  ┆ 9                ┆ 2016-02-13 │
│ Jeffrey Tanner     ┆ null       ┆ jeffrey.tanner@polars.io     ┆ 126489 ┆ 10               ┆ 2015-03-01 │
└────────────────────┴────────────┴──────────────────────────────┴────────┴──────────────────┴────────────┘

In [4]:
employees.with_columns(pl.col("salary").sort())
employees.with_columns(pl.col("salary").sort(descending=True))

shape: (1_000, 6)
┌────────────────────┬────────────┬──────────────────────────────┬────────┬──────────────────┬────────────┐
│ name               ┆ department ┆ email                        ┆ salary ┆ years_at_company ┆ start_date │
│ ---                ┆ ---        ┆ ---                          ┆ ---    ┆ ---              ┆ ---        │
│ str                ┆ str        ┆ str                          ┆ i64    ┆ i64              ┆ date       │
╞════════════════════╪════════════╪══════════════════════════════╪════════╪══════════════════╪════════════╡
│ Nicholas Maldonado ┆ CEO        ┆ nicholas.maldonado@polars.io ┆ 250000 ┆ 9                ┆ 2016-07-14 │
│ Michael Fletcher   ┆ Operations ┆ michael.fletcher@polars.io   ┆ 199503 ┆ 9                ┆ 2016-02-13 │
│ Jeffrey Tanner     ┆ null       ┆ jeffrey.tanner@polars.io     ┆ 199381 ┆ 10               ┆ 2015-03-01 │
│ Diana Weaver       ┆ HR         ┆ diana.weaver@polars.io       ┆ 199260 ┆ 5                ┆ 2019-11-25 │
│ Sierra Ross        ┆ null       ┆ sierra.ross@polars.io        ┆ 199257 ┆ 7                ┆ 2018-02-14 │
│ …                  ┆ …          ┆ …                            ┆ …      ┆ …                ┆ …          │
│ James Bryant       ┆ null       ┆ james.bryant@polars.io       ┆ 55304  ┆ 9                ┆ 2016-05-09 │
│ Patricia Vazquez   ┆ Operations ┆ patricia.vazquez@polars.io   ┆ 55242  ┆ 6                ┆ 2019-02-20 │
│ Katie Clay         ┆ null       ┆ katie.clay@polars.io         ┆ 55078  ┆ 0                ┆ 2025-02-12 │
│ Monique Swanson    ┆ Finance    ┆ monique.swanson@polars.io    ┆ 55012  ┆ 4                ┆ 2020-11-07 │
│ Christopher Lynch  ┆ null       ┆ christopher.lynch@polars.io  ┆ 55011  ┆ 3                ┆ 2022-07-04 │
└────────────────────┴────────────┴──────────────────────────────┴────────┴──────────────────┴────────────┘

#1 Eager v Lazy Evaluation

https://docs.pola.rs/user-guide/concepts/lazy-api/

df.lazy().filter(...)  # Returns LazyFrame, doesn't execute
df.lazy().filter(...).collect()  # Actually executes

In [1]:
import polars as pl

# Sample data
df = pl.DataFrame(
    {
        "name": ["Alice", "Bob", "Charlie", "David"],
        "age": [25, 30, 35, 40],
        "city": ["NYC", "LA", "NYC", "Chicago"],
    }
)

# ❌ GOTCHA: This doesn't actually filter anything!
lazy_result = df.lazy().filter(pl.col("age") > 30)
print("Lazy result (no execution):")
print(lazy_result)  # Just shows LazyFrame object
print()

Lazy result (no execution):
naive plan: (run LazyFrame.explain(optimized=True) to see the optimized plan)

FILTER [(col("age")) > (30)]
FROM
  DF ["name", "age", "city"]; PROJECT */3 COLUMNS

In [2]:
# ✅ CORRECT: You must call .collect() to execute
actual_result = df.lazy().filter(pl.col("age") > 30).collect()
print("After .collect():")
print(actual_result)
print()

After .collect():
shape: (2, 3)
┌─────────┬─────┬─────────┐
│ name    ┆ age ┆ city    │
│ ---     ┆ --- ┆ ---     │
│ str     ┆ i64 ┆ str     │
╞═════════╪═════╪═════════╡
│ Charlie ┆ 35  ┆ NYC     │
│ David   ┆ 40  ┆ Chicago │
└─────────┴─────┴─────────┘

In [3]:
# Another common mistake: chaining operations
# ❌ This builds a query plan but doesn't run it
query = df.lazy().filter(pl.col("city") == "NYC").select(["name", "age"]).sort("age")
print("Query plan (not executed):")
print(query.explain())  # Shows what WOULD be executed
print()

# ✅ Execute with .collect()
result = query.collect()
print("Executed result:")
print(result)
print()

# Pro tip: Eager operations work immediately
eager_result = df.filter(pl.col("age") > 30)  # No .lazy(), executes instantly
print("Eager evaluation (immediate):")
print(eager_result)

Query plan (not executed):
SORT BY [col("age")]
  simple π 2/2 ["name", "age"]
    FILTER [(col("city")) == ("NYC")]
    FROM
      DF ["name", "age", "city"]; PROJECT["name", "age", "city"] 3/3 COLUMNS

Executed result:
shape: (2, 2)
┌─────────┬─────┐
│ name    ┆ age │
│ ---     ┆ --- │
│ str     ┆ i64 │
╞═════════╪═════╡
│ Alice   ┆ 25  │
│ Charlie ┆ 35  │
└─────────┴─────┘

Eager evaluation (immediate):
shape: (2, 3)
┌─────────┬─────┬─────────┐
│ name    ┆ age ┆ city    │
│ ---     ┆ --- ┆ ---     │
│ str     ┆ i64 ┆ str     │
╞═════════╪═════╪═════════╡
│ Charlie ┆ 35  ┆ NYC     │
│ David   ┆ 40  ┆ Chicago │
└─────────┴─────┴─────────┘

Eager mode (df.filter(...)) executes immediately but misses optimization opportunities

In [5]:
import polars as pl

# Large dataset simulation
df = pl.DataFrame(
    {
        "user_id": range(1_000_000),
        "age": [20 + (i % 50) for i in range(1_000_000)],
        "city": [["NYC", "LA", "Chicago"][i % 3] for i in range(1_000_000)],
        "salary": [50000 + (i % 100000) for i in range(1_000_000)],
        "department": [
            ["Sales", "Engineering", "HR", "Marketing"][i % 4] for i in range(1_000_000)
        ],
    }
)

# ❌ EAGER MODE: Each operation executes immediately, one at a time
print("EAGER MODE (less efficient):")
result_eager = (
    df.filter(pl.col("age") > 30)  # Scans entire df → creates intermediate result
    .filter(pl.col("city") == "NYC")  # Scans that intermediate result
    .select(["user_id", "salary"])  # Then selects columns
    .head(100)  # Finally takes first 100
)
print(result_eager)

print("\n" + "=" * 60 + "\n")

# ✅ LAZY MODE: Polars optimizes the entire query plan BEFORE executing
print("LAZY MODE (optimized):")
result_lazy = (
    df.lazy()
    .filter(pl.col("age") > 30)
    .filter(pl.col("city") == "NYC")
    .select(["user_id", "salary"])
    .head(100)
    .collect()
)
print(result_lazy)

# What Polars optimizes:
# 1. Predicate pushdown: Combines both filters into one pass
# 2. Projection pushdown: Only reads user_id, age, city, salary (not department)
# 3. Early limit: Stops after finding 100 matching rows
# 4. Parallelization: Can process chunks in parallel

print("\n" + "=" * 60 + "\n")
print("Query plan (see the optimizations):")
print(
    df.lazy()
    .filter(pl.col("age") > 30)
    .filter(pl.col("city") == "NYC")
    .select(["user_id", "salary"])
    .head(100)
    .explain()
)

EAGER MODE (less efficient):
shape: (100, 2)
┌─────────┬────────┐
│ user_id ┆ salary │
│ ---     ┆ ---    │
│ i64     ┆ i64    │
╞═════════╪════════╡
│ 12      ┆ 50012  │
│ 15      ┆ 50015  │
│ 18      ┆ 50018  │
│ 21      ┆ 50021  │
│ 24      ┆ 50024  │
│ …       ┆ …      │
│ 375     ┆ 50375  │
│ 378     ┆ 50378  │
│ 381     ┆ 50381  │
│ 384     ┆ 50384  │
│ 387     ┆ 50387  │
└─────────┴────────┘

============================================================

LAZY MODE (optimized):
shape: (100, 2)
┌─────────┬────────┐
│ user_id ┆ salary │
│ ---     ┆ ---    │
│ i64     ┆ i64    │
╞═════════╪════════╡
│ 12      ┆ 50012  │
│ 15      ┆ 50015  │
│ 18      ┆ 50018  │
│ 21      ┆ 50021  │
│ 24      ┆ 50024  │
│ …       ┆ …      │
│ 375     ┆ 50375  │
│ 378     ┆ 50378  │
│ 381     ┆ 50381  │
│ 384     ┆ 50384  │
│ 387     ┆ 50387  │
└─────────┴────────┘

============================================================

Query plan (see the optimizations):
simple π 2/2 ["user_id", "salary"]
  SLICE[offset: 0, len: 100]
    FILTER [([(col("age")) > (30)]) & ([(col("city")) == ("NYC")])]
    FROM
      DF ["user_id", "age", "city", "salary", ...]; PROJECT["user_id", "salary", "city", "age"] 4/5 COLUMNS

Key Optimizations in Lazy Mode:

Predicate Pushdown: Combines multiple filters into one scan

python   # Eager: scan → filter age → scan → filter city
   # Lazy:  scan once with BOTH filters combined

Projection Pushdown: Only reads columns you actually need

python   # Eager: reads all 5 columns, then drops 3 later
   # Lazy:  only reads the 4 columns needed for filtering + final output

Early Termination: Stops when it has enough data

python   # Eager: processes all 1M rows, then takes first 100
   # Lazy:  stops after finding 100 matching rows
```

**Real Impact:**
```
Eager mode: 1M rows × 5 columns × 2 filter passes = lots of wasted work
Lazy mode:  ~100 rows × 4 columns × 1 filter pass = minimal work
When does it matter?

Large datasets (100k+ rows)
Multiple operations chained together
Working with many columns but only need a few
Filtering before selecting/aggregating

When is eager fine?

Small datasets
Single operations
Interactive exploration where you want immediate feedback

#2. select() vs with_columns() (working)

df.select(pl.col("a"))  # Returns ONLY column "a"
df.with_columns(pl.col("a"))  # Returns ALL columns plus modified "a"

In [1]:
# Here's a simple working example demonstrating the select() vs with_columns() gotcha in Polars:
import polars as pl

# Create a sample DataFrame
df = pl.DataFrame(
    {
        "name": ["Alice", "Bob", "Charlie"],
        "age": [25, 30, 35],
        "city": ["NYC", "LA", "Chicago"],
    }
)

print("Original DataFrame:")
print(df)
print("\n" + "=" * 50 + "\n")

Original DataFrame:
shape: (3, 3)
┌─────────┬─────┬─────────┐
│ name    ┆ age ┆ city    │
│ ---     ┆ --- ┆ ---     │
│ str     ┆ i64 ┆ str     │
╞═════════╪═════╪═════════╡
│ Alice   ┆ 25  ┆ NYC     │
│ Bob     ┆ 30  ┆ LA      │
│ Charlie ┆ 35  ┆ Chicago │
└─────────┴─────┴─────────┘

==================================================

In [8]:
# Using select() - Returns ONLY the selected column
result_select = df.select(pl.col("age") * 2)
print("Using select(pl.col('age') * 2):")
print(result_select)
print(f"Columns: {result_select.columns}")
print("\n" + "=" * 50 + "\n")

Using select(pl.col('age') * 2):
shape: (3, 1)
┌─────┐
│ age │
│ --- │
│ i64 │
╞═════╡
│ 50  │
│ 60  │
│ 70  │
└─────┘
Columns: ['age']

==================================================

In [9]:
# Using with_columns() - Returns ALL columns plus the modified one
result_with_columns = df.with_columns((pl.col("age") * 2).alias("age"))
print("Using with_columns((pl.col('age') * 2).alias('age')):")
print(result_with_columns)
print(f"Columns: {result_with_columns.columns}")

Using with_columns((pl.col('age') * 2).alias('age')):
shape: (3, 3)
┌─────────┬─────┬─────────┐
│ name    ┆ age ┆ city    │
│ ---     ┆ --- ┆ ---     │
│ str     ┆ i64 ┆ str     │
╞═════════╪═════╪═════════╡
│ Alice   ┆ 50  ┆ NYC     │
│ Bob     ┆ 60  ┆ LA      │
│ Charlie ┆ 70  ┆ Chicago │
└─────────┴─────┴─────────┘
Columns: ['name', 'age', 'city']

#3 Expression Context Matters
pl.col("a").sum()  # Works in select/group_by
pl.sum("a")  # Different! Use in different contexts

Takeaway:

pl.col() works on columns vertically; pl.sum() works across columns horizontally. They're used in different contexts for different operations.

In [13]:
import polars as pl

df = pl.DataFrame({"a": [1, 2, 3], "b": [4, 5, 6], "c": [7, 8, 9]})

In [11]:
# Expression context - vertical aggregation
df.select(pl.col("a").sum())
# Output: 6 (sum down column a: 1+2+3)

shape: (1, 1)
┌─────┐
│ a   │
│ --- │
│ i64 │
╞═════╡
│ 6   │
└─────┘

In [12]:
# Function context - horizontal aggregation
df.select(pl.sum("a", "b", "c"))
# Output:
# [12, 15, 18]  (row-wise sums: 1+4+7, 2+5+8, 3+6+9)

shape: (1, 3)
┌─────┬─────┬─────┐
│ a   ┆ b   ┆ c   │
│ --- ┆ --- ┆ --- │
│ i64 ┆ i64 ┆ i64 │
╞═════╪═════╪═════╡
│ 6   ┆ 15  ┆ 24  │
└─────┴─────┴─────┘

# 4 In Polars when using unnest functions, this is accomplished by structs which provide default column names.
See the examples below which includes an example of a structured, reusable helper function

In [14]:
employees = pl.read_csv("employees.csv", try_parse_dates=True)
employees.head(2)

shape: (2, 6)
┌────────────────────┬────────────┬──────────────────────────────┬────────┬──────────────────┬────────────┐
│ name               ┆ department ┆ email                        ┆ salary ┆ years_at_company ┆ start_date │
│ ---                ┆ ---        ┆ ---                          ┆ ---    ┆ ---              ┆ ---        │
│ str                ┆ str        ┆ str                          ┆ i64    ┆ i64              ┆ date       │
╞════════════════════╪════════════╪══════════════════════════════╪════════╪══════════════════╪════════════╡
│ Nicholas Maldonado ┆ CEO        ┆ nicholas.maldonado@polars.io ┆ 250000 ┆ 9                ┆ 2016-07-14 │
│ Michael Fletcher   ┆ Operations ┆ michael.fletcher@polars.io   ┆ 96540  ┆ 9                ┆ 2016-02-13 │
└────────────────────┴────────────┴──────────────────────────────┴────────┴──────────────────┴────────────┘

In [15]:
# The column name label is "count"
employees.select(pl.col("department").value_counts()).unnest(pl.col("department"))

shape: (8, 2)
┌─────────────┬───────┐
│ department  ┆ count │
│ ---         ┆ ---   │
│ str         ┆ u32   │
╞═════════════╪═══════╡
│ HR          ┆ 150   │
│ Marketing   ┆ 146   │
│ Finance     ┆ 144   │
│ Sales       ┆ 129   │
│ null        ┆ 155   │
│ CEO         ┆ 1     │
│ Engineering ┆ 139   │
│ Operations  ┆ 136   │
└─────────────┴───────┘

In [17]:
# The autogenerated coumn name label is "proportion"
employees.select(pl.col("department").value_counts(sort=True, normalize=True)).unnest(
    pl.col("department")
)

shape: (8, 2)
┌─────────────┬────────────┐
│ department  ┆ proportion │
│ ---         ┆ ---        │
│ str         ┆ f64        │
╞═════════════╪════════════╡
│ null        ┆ 0.155      │
│ HR          ┆ 0.15       │
│ Marketing   ┆ 0.146      │
│ Finance     ┆ 0.144      │
│ Engineering ┆ 0.139      │
│ Operations  ┆ 0.136      │
│ Sales       ┆ 0.129      │
│ CEO         ┆ 0.001      │
└─────────────┴────────────┘

In [18]:
# The autogenerated column can be renamed easily
employees.select(pl.col("department").value_counts(sort=True, normalize=True)).unnest(
    "department"
).rename({"proportion": "pct"})

shape: (8, 2)
┌─────────────┬───────┐
│ department  ┆ pct   │
│ ---         ┆ ---   │
│ str         ┆ f64   │
╞═════════════╪═══════╡
│ null        ┆ 0.155 │
│ HR          ┆ 0.15  │
│ Marketing   ┆ 0.146 │
│ Finance     ┆ 0.144 │
│ Engineering ┆ 0.139 │
│ Operations  ┆ 0.136 │
│ Sales       ┆ 0.129 │
│ CEO         ┆ 0.001 │
└─────────────┴───────┘

In [21]:
# Creating a helper function 

import polars as pl


def vc(df, column, normalize=True, count_name="count", prop_name="proportion"):
    """
    A reusable helper for Polars value_counts with clean renaming.

    Parameters
    ----------
    df : pl.DataFrame
        The input DataFrame.
    column : str
        Column to compute value counts on.
    normalize : bool, default True
        Whether to compute proportions.
    count_name : str, default "count"
        Name for the count column.
    prop_name : str, default "proportion"
        Name for the proportion column.
    """
    return (
        df.select(pl.col(column).value_counts(sort=True, normalize=normalize))
        .unnest(column)
        .rename({"count": count_name, "proportion": prop_name})
    )

In [22]:
# Executing the helper function
vc(employees, "department", normalize=True, prop_name="pct")

shape: (8, 2)
┌─────────────┬───────┐
│ department  ┆ pct   │
│ ---         ┆ ---   │
│ str         ┆ f64   │
╞═════════════╪═══════╡
│ null        ┆ 0.155 │
│ HR          ┆ 0.15  │
│ Marketing   ┆ 0.146 │
│ Finance     ┆ 0.144 │
│ Engineering ┆ 0.139 │
│ Operations  ┆ 0.136 │
│ Sales       ┆ 0.129 │
│ CEO         ┆ 0.001 │
└─────────────┴───────┘

#5  Row Indexing Different from Pandas 
df[0]  # Returns first ROW as DataFrame (not Series!)
df[0, 0]  # Returns scalar value
df[:, 0]  # Returns first column

Polars and Pandas use completely different indexing conventions - what gets you a column in Pandas gets you a row in Polars!

Polars uses [row, column] notation (like NumPy), while Pandas uses [column] for bracket indexing (rows need .iloc).
Tip: In Polars, avoid bracket indexing altogether - use explicit methods like .select(), .filter(), .row() for clarity!

In [28]:
# 5: Row Indexing Different from Pandas

import pandas as pd
import polars as pl

# Sample data
data = {
    "name": ["Alice", "Bob", "Charlie"],
    "age": [25, 30, 35],
    "city": ["NYC", "LA", "Chicago"],
}

# Create DataFrames
df_polars = pl.DataFrame(data)
df_pandas = pd.DataFrame(data)

print("=== PANDAS INDEXING ===")
print("\ndf[0] → ERROR! (KeyError: 0)")
# print(df_pandas[0])  # This fails!

print("\ndf['name'] → First column (Series)")
print(df_pandas["name"])
print(type(df_pandas["name"]))  # <class 'pandas.core.series.Series'>

print("\ndf.iloc[0] → First row (Series)")
print(df_pandas.iloc[0])
print(type(df_pandas.iloc[0]))  # <class 'pandas.core.series.Series'>

print("\n" + "=" * 50)
print("=== POLARS INDEXING ===")

print("\ndf[0] → First ROW as DataFrame!")
print(df_polars[0])
print(type(df_polars[0]))  # <class 'polars.dataframe.frame.DataFrame'>

print("\ndf[0, 0] → Scalar value (first row, first column)")
print(df_polars[0, 0])  # "Alice"
print(type(df_polars[0, 0]))  # <class 'str'>

print("\ndf[:, 0] → First COLUMN as DataFrame")
print(df_polars[:, 0])
print(type(df_polars[:, 0]))  # <class 'polars.dataframe.frame.DataFrame'>

print("\ndf[:, 'name'] → Column by name")
print(df_polars[:, "name"])

=== PANDAS INDEXING ===

df[0] → ERROR! (KeyError: 0)

df['name'] → First column (Series)
0      Alice
1        Bob
2    Charlie
Name: name, dtype: str
<class 'pandas.Series'>

df.iloc[0] → First row (Series)
name    Alice
age        25
city      NYC
Name: 0, dtype: object
<class 'pandas.Series'>

==================================================
=== POLARS INDEXING ===

df[0] → First ROW as DataFrame!
shape: (1, 3)
┌───────┬─────┬──────┐
│ name  ┆ age ┆ city │
│ ---   ┆ --- ┆ ---  │
│ str   ┆ i64 ┆ str  │
╞═══════╪═════╪══════╡
│ Alice ┆ 25  ┆ NYC  │
└───────┴─────┴──────┘
<class 'polars.dataframe.frame.DataFrame'>

df[0, 0] → Scalar value (first row, first column)
Alice
<class 'str'>

df[:, 0] → First COLUMN as DataFrame
shape: (3,)
Series: 'name' [str]
[
	"Alice"
	"Bob"
	"Charlie"
]
<class 'polars.series.series.Series'>

df[:, 'name'] → Column by name
shape: (3,)
Series: 'name' [str]
[
	"Alice"
	"Bob"
	"Charlie"
]

#6 In Polars, nothing modifies a DataFrame in place — every operation returns a new DataFrame and leaves the original untouched. This is different from pandas, where many operations have an inplace=True option.

Why Polars works this way:

This is called immutability — the original DataFrame is never mutated. It's a deliberate design choice that makes code safer and more predictable. You always know df hasn't changed unless you explicitly reassigned it. It also enables Polars' lazy evaluation and query optimization under the hood.
A useful habit is to think of every Polars method as returning a brand new DataFrame rather than modifying the existing one.

To determine if there is an in-place operator in Polars, consider the following points:

Polars does not have traditional in-place operators like some other libraries.
Operations in Polars typically return new DataFrames rather than modifying existing ones.
You can use methods like .with_columns() to add or modify columns efficiently.
The .select() method allows for selecting and transforming columns in a new DataFrame.
For performance, Polars uses lazy evaluation, optimizing operations before execution.
Always refer to the latest Polars documentation for updates on features and functionalities.

In [2]:
import polars as pl

df = pl.DataFrame({"name": ["Charlie", "Alice", "Bob"], "score": [85, 92, 78]})

df.sort("score")  # ← This runs fine but the result is thrown away!

print(df)  # df is still in the original unsorted order

shape: (3, 2)
┌─────────┬───────┐
│ name    ┆ score │
│ ---     ┆ ---   │
│ str     ┆ i64   │
╞═════════╪═══════╡
│ Charlie ┆ 85    │
│ Alice   ┆ 92    │
│ Bob     ┆ 78    │
└─────────┴───────┘

In [3]:
df = df.sort("score")  # ← capture the new sorted DataFrame

print(df)

shape: (3, 2)
┌─────────┬───────┐
│ name    ┆ score │
│ ---     ┆ ---   │
│ str     ┆ i64   │
╞═════════╪═══════╡
│ Bob     ┆ 78    │
│ Charlie ┆ 85    │
│ Alice   ┆ 92    │
└─────────┴───────┘

#7 In Polars, when selecting multiple columns, you must pass them as a single list — you cannot pass them as separate positional arguments like you might be used to in Pandas.

Why it Happens
Polars' .select() method expects its argument to be a single expression or a list of expressions/strings. Passing multiple positional arguments like df.select("a", "b") either throws an error or silently behaves unexpectedly depending on the Polars version.

One column? String is fine → df.select("a")
Multiple columns? Always use a list → df.select(["a", "b"])

In [1]:
import polars as pl

df = pl.DataFrame({"a": [1, 2, 3], "b": [4, 5, 6], "c": [7, 8, 9]})

# ✅ Correct — pass columns as a list
print(df.select(["a", "b"]))

# ✅ Also correct — using Polars expressions as a list
print(df.select([pl.col("a"), pl.col("b")]))

# ❌ Wrong — multiple positional arguments (doesn't work like Pandas)
# print(df.select("a", "b"))  # TypeError

shape: (3, 2)
┌─────┬─────┐
│ a   ┆ b   │
│ --- ┆ --- │
│ i64 ┆ i64 │
╞═════╪═════╡
│ 1   ┆ 4   │
│ 2   ┆ 5   │
│ 3   ┆ 6   │
└─────┴─────┘
shape: (3, 2)
┌─────┬─────┐
│ a   ┆ b   │
│ --- ┆ --- │
│ i64 ┆ i64 │
╞═════╪═════╡
│ 1   ┆ 4   │
│ 2   ┆ 5   │
│ 3   ┆ 6   │
└─────┴─────┘

#8 Explanation
None / NULL

Represents missing data — the value simply doesn't exist
Can exist in any data type (strings, ints, floats)
Caught by is_null()

NaN (Not a Number)

Represents an invalid float computation (e.g. 0/0, sqrt(-1))
Only exists in float columns
Caught by is_nan()

# If you only check is_null(), you'll MISS NaN values
df.filter(pl.col("values").is_null())  # ❌ Misses NaN rows

# If you want to catch BOTH, combine them
df.filter(
    pl.col("values").is_null() | pl.col("values").is_nan()
)  # ✅ Catches everything missing/invalid

In [4]:
import math

import polars as pl

# Create DataFrame with BOTH null and NaN values
df = pl.DataFrame(
    {"values": pl.Series([1.0, None, float("nan"), 4.0, float("nan"), None])}
)

print("Original DataFrame:")
print(df)

# Check is_null()
print("\nis_null() - catches None/NULL only:")
print(df.with_columns(pl.col("values").is_null().alias("is_null")))

# Check is_nan()
print("\nis_nan() - catches NaN only:")
print(df.with_columns(pl.col("values").is_nan().alias("is_nan")))

# Show both side by side
print("\nSide by side comparison:")
print(
    df.with_columns(
        [
            pl.col("values").is_null().alias("is_null"),
            pl.col("values").is_nan().alias("is_nan"),
        ]
    )
)

Original DataFrame:
shape: (6, 1)
┌────────┐
│ values │
│ ---    │
│ f64    │
╞════════╡
│ 1.0    │
│ null   │
│ NaN    │
│ 4.0    │
│ NaN    │
│ null   │
└────────┘

is_null() - catches None/NULL only:
shape: (6, 2)
┌────────┬─────────┐
│ values ┆ is_null │
│ ---    ┆ ---     │
│ f64    ┆ bool    │
╞════════╪═════════╡
│ 1.0    ┆ false   │
│ null   ┆ true    │
│ NaN    ┆ false   │
│ 4.0    ┆ false   │
│ NaN    ┆ false   │
│ null   ┆ true    │
└────────┴─────────┘

is_nan() - catches NaN only:
shape: (6, 2)
┌────────┬────────┐
│ values ┆ is_nan │
│ ---    ┆ ---    │
│ f64    ┆ bool   │
╞════════╪════════╡
│ 1.0    ┆ false  │
│ null   ┆ null   │
│ NaN    ┆ true   │
│ 4.0    ┆ false  │
│ NaN    ┆ true   │
│ null   ┆ null   │
└────────┴────────┘

Side by side comparison:
shape: (6, 3)
┌────────┬─────────┬────────┐
│ values ┆ is_null ┆ is_nan │
│ ---    ┆ ---     ┆ ---    │
│ f64    ┆ bool    ┆ bool   │
╞════════╪═════════╪════════╡
│ 1.0    ┆ false   ┆ false  │
│ null   ┆ true    ┆ null   │
│ NaN    ┆ false   ┆ true   │
│ 4.0    ┆ false   ┆ false  │
│ NaN    ┆ false   ┆ true   │
│ null   ┆ true    ┆ null   │
└────────┴─────────┴────────┘

```

**Output:**
```
Original DataFrame:
┌────────┐
│ values │
│ ---    │
│ f64    │
╞════════╡
│ 1.0    │
│ null   │
│ NaN    │
│ 4.0    │
│ NaN    │
│ null   │
└────────┘

Side by side comparison:
┌────────┬─────────┬────────┐
│ values ┆ is_null ┆ is_nan │
│ ---    ┆ ---     ┆ ---    │
│ f64    ┆ bool    ┆ bool   │
╞════════╪═════════╪════════╡
│ 1.0    ┆ false   ┆ false  │
│ null   ┆ true    ┆ false  │  ← null caught by is_null only
│ NaN    ┆ false   ┆ true   │  ← NaN caught by is_nan only
│ 4.0    ┆ false   ┆ false  │
│ NaN    ┆ false   ┆ true   │  ← NaN caught by is_nan only
│ null   ┆ true    ┆ false  │  ← null caught by is_null only
└────────┴─────────┴────────┘

#9 Polars uses its own type system — it doesn't understand native Python types like int, float, str. You must always use pl. prefixed dtypes.

In [9]:
import polars as pl

# Sample DataFrame with mixed-looking data
df = pl.DataFrame(
    {
        "scores": [1.5, 2.7, 3.9, 4.1, 5.8],
        "readings": ["100", "200", "300", "400", "500"],  # strings that look like ints
        "frequency": [440.5, 880.1, 220.3, 110.7, 55.2],
    }
)

print("Original dtypes:")
print(df.dtypes)
print(df)

Original dtypes:
[Float64, String, Float64]
shape: (5, 3)
┌────────┬──────────┬───────────┐
│ scores ┆ readings ┆ frequency │
│ ---    ┆ ---      ┆ ---       │
│ f64    ┆ str      ┆ f64       │
╞════════╪══════════╪═══════════╡
│ 1.5    ┆ 100      ┆ 440.5     │
│ 2.7    ┆ 200      ┆ 880.1     │
│ 3.9    ┆ 300      ┆ 220.3     │
│ 4.1    ┆ 400      ┆ 110.7     │
│ 5.8    ┆ 500      ┆ 55.2      │
└────────┴──────────┴───────────┘

In [10]:
# These all raise InvalidOperationError or TypeError

try:
    df.with_columns(pl.col("scores").cast(int))  # Python built-in int
except Exception as e:
    print(f"cast(int) failed:     {type(e).__name__}: {e}")

try:
    df.with_columns(pl.col("scores").cast(float))  # Python built-in float
except Exception as e:
    print(f"cast(float) failed:   {type(e).__name__}: {e}")

try:
    df.with_columns(pl.col("readings").cast(str))  # Python built-in str
except Exception as e:
    print(f"cast(str) failed:     {type(e).__name__}: {e}")

In [11]:
result = df.with_columns(
    [
        # Float → Integer
        pl.col("scores").cast(pl.Int64).alias("scores_int"),
        # Float → 32-bit float (reduce precision/memory)
        pl.col("frequency").cast(pl.Float32).alias("freq_f32"),
        # String → Integer
        pl.col("readings").cast(pl.Int32).alias("readings_int"),
        # Integer → String
        pl.col("readings").cast(pl.Utf8).alias("readings_str"),
        # Float → Boolean (0.0 = False, anything else = True)
        pl.col("scores").cast(pl.Boolean).alias("scores_bool"),
    ]
)

print("\nAfter casting:")
print(result)
print("\nNew dtypes:")
print(result.dtypes)

After casting:
shape: (5, 8)
┌────────┬──────────┬───────────┬────────────┬────────────┬──────────────┬──────────────┬─────────────┐
│ scores ┆ readings ┆ frequency ┆ scores_int ┆ freq_f32   ┆ readings_int ┆ readings_str ┆ scores_bool │
│ ---    ┆ ---      ┆ ---       ┆ ---        ┆ ---        ┆ ---          ┆ ---          ┆ ---         │
│ f64    ┆ str      ┆ f64       ┆ i64        ┆ f32        ┆ i32          ┆ str          ┆ bool        │
╞════════╪══════════╪═══════════╪════════════╪════════════╪══════════════╪══════════════╪═════════════╡
│ 1.5    ┆ 100      ┆ 440.5     ┆ 1          ┆ 440.5      ┆ 100          ┆ 100          ┆ true        │
│ 2.7    ┆ 200      ┆ 880.1     ┆ 2          ┆ 880.099976 ┆ 200          ┆ 200          ┆ true        │
│ 3.9    ┆ 300      ┆ 220.3     ┆ 3          ┆ 220.300003 ┆ 300          ┆ 300          ┆ true        │
│ 4.1    ┆ 400      ┆ 110.7     ┆ 4          ┆ 110.699997 ┆ 400          ┆ 400          ┆ true        │
│ 5.8    ┆ 500      ┆ 55.2      ┆ 5          ┆ 55.200001  ┆ 500          ┆ 500          ┆ true        │
└────────┴──────────┴───────────┴────────────┴────────────┴──────────────┴──────────────┴─────────────┘

New dtypes:
[Float64, String, Float64, Int64, Float32, Int32, String, Boolean]

Polars is built in Rust and maps to Arrow memory types internally. When you write pl.Int64, Polars maps this to a specific Arrow int64 buffer. Python's native int is an object with arbitrary precision — it has no direct Arrow equivalent, so Polars simply doesn't accept it. The strict=False flag is especially useful when working with real-world messy data like sensor readings or atmospheric recordings.

In [12]:
dirty = pl.DataFrame(
    {
        "values": ["123", "456", "oops", "789", "???"]  # contains non-numeric
    }
)

# ❌ This will raise an error
# try:
#    dirty.with_columns(pl.col("values").cast(pl.Int64))
# except Exception as e:
#    print(f"Strict cast failed: {e}")

# ✅ Use strict=False to return null instead of crashing
safe = dirty.with_columns(
    pl.col("values").cast(pl.Int64, strict=False).alias("safe_int")
)
print("\nSafe cast result (nulls instead of errors):")
print(safe)

Safe cast result (nulls instead of errors):
shape: (5, 2)
┌────────┬──────────┐
│ values ┆ safe_int │
│ ---    ┆ ---      │
│ str    ┆ i64      │
╞════════╪══════════╡
│ 123    ┆ 123      │
│ 456    ┆ 456      │
│ oops   ┆ null     │
│ 789    ┆ 789      │
│ ???    ┆ null     │
└────────┴──────────┘